version: '3.8'

services:
  neo4j:
    image: neo4j:5.13.0
    container_name: planificador-neo4j
    ports:
      - "7474:7474"  # Browser web de Neo4j
      - "7687:7687"  # Puerto Bolt
    environment:
      - NEO4J_AUTH=neo4j/grupo123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - planificador-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planificador-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=grupo123
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - planificador-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  planificador-network:
    driver: bridge

